version: '3.7'

services:
  user-api-mysql:
    image: mysql:8.0@sha256:c35eb76bbccfd0138c8c68ccb9b4cffe42c488a27f64ddc31a2b5f65aa93fce6
    ports:
      - published: ${USER_API_MYSQL_PORT}
        target: 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${USER_API_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${USER_API_MYSQL_DATABASE}
    volumes:
      - user-api-mysql-data:/var/lib/mysql

volumes:
  user-api-mysql-data:
